### ISSUE TITLE
天气预报只能先是实时天气

### ISSUE THREAD

**Issue by 467815891a** [HelloWk/MagicMirror#2]
感谢作者的辛勤劳动，我右上角的天气只能显示单元的，readme里面的图明明有5天预报，我申请的是免费的API接口，但是也应该支持5天天气预报呀。

**Comment by 467815891a** [comment]
把日历ics文件的url填进去好像也没有用😭

**Comment by HelloWk** [comment]
你好，这个项目是我二年前做的，目前由于其他原因已经把魔镜撤掉了，所以具体什么原因我没有办法测试，如果你希望解决此问题，那么欢迎加入 QQ 群（群号:137605115）和小伙伴一起讨论。

**Comment by 467815891a** [comment]
感谢，自己找到了原因，API请求的地址有些变动，forecastendpoint改为'forecast'，数据格式也变了，稍微改一下就好了，感谢回复😊
