### ISSUE TITLE
新版的MagicMirror使用了模拟器，相比打开chrome访问固定网址，占用的cpu更高，发热比较大，所以最后还是采用了原始的方式是直接在浏览器打开然后按F11全屏吗

### ISSUE THREAD

**Issue by 123xiao** [HelloWk/MagicMirror#4]

**Comment by HelloWk** [comment]
有自动开机启动并全屏的代码：

`
修改这个文件：

~/.config/lxsession/LXDE-pi/autostart
在 @xscreensaver -no-splash 前面加上 # 号。
加入以下代码：

@xset s off
@xset -dpms
@xset s noblank
@chromium-browser --kiosk --incognito http://localhost
这样就能完全禁用所有屏保功能，及 Chromium 浏览器在开机后自动启动，开启全屏模式并导向本地主页。
`

参考此文： [使用树莓派制作一个魔镜1（硬件制作和环境搭建）](http://www.hellowk.cc/14834426274852.html)

、、具体需要自己测试，我不知道现在的环境设置是否一样。
